import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useEffect, useCallback } from "react";
import NumberButton from "@components/NumberButton";
import NumberDisplay from "@components/NumberDisplay";
import OperatorButton from "@components/OperatorButton";
import { app } from "../firebase/firebase";
import {
  getFirestore,
  collection,
  doc,
  getDocs,
  setDoc,
} from "firebase/firestore";

const Home: NextPage = () => {
  const [display, setDisplay] = useState("");
  const [lastOperator, setLastOperator] = useState<string | null>(null);
  const [isLastInputOperator, setIsLastInputOperator] = useState<
    boolean | null
  >(null);
  const [numberMainBox, setNumberMainBox] = useState<number | null>(null);

  useEffect(() => {
    const db = getFirestore(app);
    getDocs(collection(db, "higuchi")).then((querySnapshot: any) => {
      querySnapshot.forEach((doc: any) => {
        console.log(`${doc.id} | ${doc.data().age}`);
      });
    });

    setDoc(doc(collection(db, "higuchi"), "kazuya"), { age: 51 });
  }, []);

  const pressNumber = useCallback(
    (number: number) => {
      if (isLastInputOperator) {
        setIsLastInputOperator(false);

        setNumberMainBox(Number(`${display}`));
        setDisplay(`${number}`);
      } else {
        setDisplay((current) => `${current}${number}`);
      }
    },
    [isLastInputOperator]
  );

  const calculate = (operator: string, num1: number, num2: number): number => {
    switch (operator) {
      case "+":
        return num1 + num2;
      case "-":
        return num1 - num2;
      case "×":
        return num1 * num2;
      case "÷":
        return num1 / num2;
      default:
        return num1;
    }
  };

  const pressOperator = (operator: string) => {
    if (numberMainBox) {
      const calcResult = calculate(
        lastOperator!,
        numberMainBox,
        Number(display)
      );

      setNumberMainBox(calcResult);
      setDisplay(`${calcResult}`);
    }

    setLastOperator(operator);
    setIsLastInputOperator(true);

    if (operator === "🐰") {
      // XXX: setNumberMainBoxの直後、numberMainBoxが更新されてるとは限らない
      setNumberMainBox(null);
      setDisplay("");
      setLastOperator(null);
      setIsLastInputOperator(false);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>電卓</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <div className="grid grid-cols-4 gap-3">
            <NumberDisplay display={display} />
            <NumberButton num={7} onPressNumber={pressNumber} />
            <NumberButton num={8} onPressNumber={pressNumber} />
            <NumberButton num={9} onPressNumber={pressNumber} />
            <OperatorButton operator={"🐰"} onPressOperator={pressOperator} />
            <NumberButton num={4} onPressNumber={pressNumber} />
            <NumberButton num={5} onPressNumber={pressNumber} />
            <NumberButton num={6} onPressNumber={pressNumber} />
            <OperatorButton operator={"="} onPressOperator={pressOperator} />
            <NumberButton num={1} onPressNumber={pressNumber} />
            <NumberButton num={2} onPressNumber={pressNumber} />
            <NumberButton num={3} onPressNumber={pressNumber} />
            <OperatorButton operator={"+"} onPressOperator={pressOperator} />
            <NumberButton num={0} onPressNumber={pressNumber} />
            <OperatorButton operator={"÷"} onPressOperator={pressOperator} />
            <OperatorButton operator={"×"} onPressOperator={pressOperator} />
            <OperatorButton operator={"-"} onPressOperator={pressOperator} />
          </div>
        </h1>
      </main>
    </div>
  );
};

export default Home;
